name: Keep Streamlit App Awake

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

permissions:
  contents: write 

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Create empty commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit --allow-empty -m "Auto Empty Commit to Keep Streamlit up"
          git push
